name = "TinyGismo"
uuid = "5750890c-44ac-400c-9e9d-1788b5a8ead6"
version = "0.1.0"
authors = ["Henrik Jakob <jakob@ibb.uni-stuttgart.de>"]

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
TinyGismo_jll = "7e61441e-6e6e-5c6f-8c66-76107880e13d"

[compat]
CxxWrap = "0.17.4"
EnumX = "1.0.5"
TinyGismo_jll = "0.1.4"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Test", "Aqua", "TestItems", "TestItemRunner"]
